### PR TITLE
Avoid return of both error and result

### PR DESCRIPTION
**Pull request by 3schwartz**
In some cases both errors and result with re-queue was returned. This gave error

```
INFO    Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler 
```

Changed to only returning the error and really on the controllers exponential backoff.

Also made the time between reconciliations configurable through environment variable `REQUEUE_AFTER`.

### CODE REVIEW

**Comment by jcchavezs** [comment]
I am usually in favor of including the units in the name for time variables, `REQUEUE_AFTER=2` does not tell anything, shall we use `REQUEUE_AFTER_MS` or `REQUEUE_AFTER_SECS` or just call `REQUEUE_AFTER` and specify it is seconds an only attempt to parse integers.

**Comment by 3schwartz** [comment]
> my 2p: I am usually in favor of including the units in the name for time variables, `REQUEUE_AFTER=2` does not tell anything, shall we use `REQUEUE_AFTER_MS` or `REQUEUE_AFTER_SECS` or just call `REQUEUE_AFTER` and specify it is seconds an only attempt to parse integers.

Great comment and I agree 👏

I chose to suffix the environment variable with _DURATION to indicate flexibility in the time unit, allowing any valid duration value to be parsed successfully. This avoids binding the variable to a specific time unit.

**Comment by jcchavezs** [comment]
> I chose to suffix the environment variable with _DURATION to indicate flexibility in the time unit, allowing any valid duration value to be parsed successfully. This avoids binding the variable to a specific time unit.

Sounds useful but ambiguous so I suggest we document it extensively with examples.

**Comment by 3schwartz** [comment]
> > I chose to suffix the environment variable with _DURATION to indicate flexibility in the time unit, allowing any valid duration value to be parsed successfully. This avoids binding the variable to a specific time unit.
> 
> Sounds useful but ambiguous so I suggest we document it extensively with examples.

Added documentation for configuration both from flags and environment variables.

**Pull request merged**
